[package]
name = "law_of_large_numbers_approximation"
version = "0.1.0"
authors = ["mfurak"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"